Created profile screen, add styles for views
Ra53n/Charge_it pull request #10
Opened 2022-11-13 16:08 UTC by Oduvan58

Прошу проверить выполненное задание. Создал экран для профиля, вынес в стили и ресурсы все значения

2022-11-14 16:32 UTC, Ra53n requested changes

2022-11-14 16:32 UTC, Ra53n commented on core/src/main/res/values/styles.xml
> +        <item name="android:layout_width">wrap_content</item>
Необязательно в стили выносить высоту и ширину. Принято в стили выносить какие-то атрибуты по типу стиль текста, размер текста и т.д. Это делается для универсальности и переиспользования на различных экранах.

2022-11-14 16:32 UTC, Ra53n commented on profileScreen/proguard-rules.pro
> +# For more details, see
Этот файл можешь удалить

2022-11-14 16:32 UTC, Ra53n commented on core/src/main/res/values/styles.xml
> +        <item name="android:layout_width">wrap_content</item>
Вообще я имел ввиду просто вынести все параметры текста в стиль и каждый раз его использовать. Если для каждой вью делать стиль, то у тебя будет огромный список стилей и разобраться в нем станет очень тяжело. Поэтому лучше верни все параметры связанные с layout обратно в экран и оставь только стили для текста здесь. У тебя получится там 1-2 стиля и все станет гораздо читабельнее.

2022-11-14 16:32 UTC, Ra53n commented on profileScreen/build.gradle
> +    implementation 'com.google.android.material:material:1.7.0'
Эти библиотеки уже добавлены в проект. CardView уже лежит в material библиотеке. Тебе достаточно добавить две строки 
`implementation libraries.constraintLayout
implementation libraries.material`

2022-11-14 17:38 UTC, Oduvan58 commented on core/src/main/res/values/styles.xml
> +        <item name="android:layout_width">wrap_content</item>
Исправил

2022-11-14 17:38 UTC, Oduvan58 commented on profileScreen/proguard-rules.pro
> +# For more details, see
Исправил

2022-11-14 17:38 UTC, Oduvan58 commented on profileScreen/build.gradle
> +    implementation 'com.google.android.material:material:1.7.0'
Исправил

2022-11-14 17:59 UTC, Ra53n requested changes

2022-11-14 17:59 UTC, Ra53n commented on core/src/main/res/values/styles.xml
>          <item name="android:layout_marginStart">@dimen/margin_20</item>
Маргины тоже во вью надо унести

2022-11-14 17:59 UTC, Ra53n commented on core/src/main/res/values/styles.xml
> -        <item name="android:textColor">@color/text_color_titles_info</item>
Цвет текста можешь оставить

2022-11-14 17:59 UTC, Ra53n commented on core/src/main/res/values/styles.xml
>          <item name="android:layout_marginStart">@dimen/margin_20</item>
Тоже не убрал

2022-11-14 17:59 UTC, Ra53n commented on core/src/main/res/values/styles.xml
>          <item name="android:layout_marginStart">@dimen/margin_20</item>
Маргины

2022-11-19 12:14 UTC, Oduvan58 commented on core/src/main/res/values/styles.xml
>          <item name="android:layout_marginStart">@dimen/margin_20</item>
Исправил

2022-11-19 12:14 UTC, Oduvan58 commented on core/src/main/res/values/styles.xml
>          <item name="android:layout_marginStart">@dimen/margin_20</item>
исправил

2022-11-19 12:14 UTC, Oduvan58 commented on core/src/main/res/values/styles.xml
>          <item name="android:layout_marginStart">@dimen/margin_20</item>
исправил

2022-11-19 12:15 UTC, Oduvan58 commented on core/src/main/res/values/styles.xml
> -        <item name="android:textColor">@color/text_color_titles_info</item>
исправил

2022-12-04 15:47 UTC, Ra53n approved these changes

2022-12-04 15:47 UTC, merged