Created database, repos, dao, models, entities, mappers
Ra53n/Charge_it pull request #11
Opened 2022-11-14 17:12 UTC by Oduvan58

Прошу проверить доработку базы данных

2022-11-14 17:33 UTC, Ra53n requested changes

2022-11-14 17:33 UTC, Ra53n commented on data/src/main/java/chargeit/data/domain/model/CarEntity.kt
> +    val listOfSockets: List<SocketModel>,
У тебя он должен ссылать не на модель, а тоже на Entity. Тебе нужно все эти преобразования делать в mapper-ах. Если mapper требует какого-то еще mapper-а, то передавай нужный через di.

2022-11-14 17:33 UTC, Ra53n commented on data/src/main/java/chargeit/data/room/mappers/CarMapper.kt
> +    fun toCarModel(car: CarEntity): CarModel {
По сути тебе не нужно будет обратного преобразования в модель. Все данные, которые мы будем заносить, будут сразу создаваться как Model. В каждом маппере можно оставить только функцию map

2022-11-14 17:33 UTC, Ra53n commented on data/src/main/java/chargeit/data/room/mappers/CarMapper.kt
> +class CarMapper {
Лучше переименовать мапперы в ...ModelToEntityMapper и оставить в ней только одну функцию map (переименую функцию toCarEntity). Такой нэйминг позволит любому разработчику из команды быстро найти нужный ему маппер по всему проекту.

2022-11-14 17:33 UTC, Ra53n commented on data/proguard-rules.pro
> +# class:
Можешь удалить

2022-11-14 17:33 UTC, Ra53n commented on data/proguard-rules.pro
> +# debugging stack traces.
Тоже можешь удалить

2022-11-14 17:33 UTC, Ra53n commented on data/src/main/java/chargeit/data/room/mappers/SocketMapper.kt
> +class SocketMapper {
По сути это будет у тебя маппер, который почти во все остальные будет передаваться

2022-11-14 17:33 UTC, Ra53n commented on data/src/main/java/chargeit/data/room/mappers/SocketMapper.kt
> +class SocketMapper {
В CarMapper и ElectricStationMapper передавай этот маппер. А в UserMapper передавай CarMapper

2022-11-14 17:33 UTC, Ra53n commented on data/src/main/java/chargeit/data/room/mappers/SocketMapper.kt
> +class SocketMapper {
Тогда у тебя Entity избавятся от моделей БД

2022-11-14 18:00 UTC, Oduvan58 commented on data/src/main/java/chargeit/data/room/mappers/CarMapper.kt
> +class CarMapper {
Исправил

2022-11-14 18:00 UTC, Oduvan58 commented on data/proguard-rules.pro
> +# class:
Исправил

2022-11-14 18:00 UTC, Oduvan58 commented on data/proguard-rules.pro
> +# debugging stack traces.
Исправил

2022-11-14 18:02 UTC, Oduvan58 commented on data/src/main/java/chargeit/data/room/mappers/CarMapper.kt
> +    fun toCarModel(car: CarEntity): CarModel {
Исправил

2022-11-18 17:50 UTC, Oduvan58 commented on data/src/main/java/chargeit/data/domain/model/CarEntity.kt
> +    val listOfSockets: List<SocketModel>,
Исправлено

2022-11-18 17:51 UTC, Oduvan58 commented on data/src/main/java/chargeit/data/room/mappers/SocketMapper.kt
> +class SocketMapper {
Исправил

2022-11-19 10:16 UTC, closed without merging