Feature/main screen
Ra53n/Charge_it pull request #16
Opened 2022-11-23 15:45 UTC by Stellarworker

Небольшие изменения:
1. Реализована кластеризация иконок на карте
2. Скорректированы размеры SearchView и filterScreenButton
3. Скорректированы некоторые цвета для корректного отображения элементов

2022-11-26 07:47 UTC, Ra53n requested changes

2022-11-26 07:47 UTC, Ra53n commented on app/build.gradle
> +    implementation project(path: ':main_screen')
Тут второй импорт

2022-11-26 07:47 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +        val noRationale = !shouldShowAtLeastOneRationale()
Можешь вместо восклицательного знака поставить в конце .not()

2022-11-26 07:47 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +        clusterManager = ClusterManager(context, map)
Разбей на функции, не совсем понятно что здесь происходит

2022-11-26 07:47 UTC, Ra53n commented on core/src/main/java/chargeit/core/view/CoreFragment.kt
> +}
Тут пробелы добавились

2022-11-26 07:47 UTC, Ra53n commented on main_screen/src/main/res/values/dimens.xml
> +    <dimen name="search_margin_bottom">20dp</dimen>
Тебе не обязательно на каждую вещь делать разные ресурсы. Ты можешь сделать допустим margin_20 и использовать это значение везде где тебе нужно margin 20.

2022-11-30 08:07 UTC, Stellarworker commented on app/build.gradle
> +    implementation project(path: ':main_screen')
Убрал

2022-11-30 08:07 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +        val noRationale = !shouldShowAtLeastOneRationale()
Заменил

2022-11-30 08:07 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +        clusterManager = ClusterManager(context, map)
Разбил

2022-11-30 08:07 UTC, Stellarworker commented on core/src/main/java/chargeit/core/view/CoreFragment.kt
> +}
Убрал

2022-11-30 08:08 UTC, Stellarworker commented on main_screen/src/main/res/values/dimens.xml
> +    <dimen name="search_margin_bottom">20dp</dimen>
Можно

2022-12-01 14:49 UTC, Ra53n requested changes

2022-12-01 14:49 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/maps/MapsFragmentViewModel.kt
> +    private fun getBitmapDescriptorFromVector(
Это можно в утилиту отдельную унести

2022-12-01 14:49 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/maps/MapsFragmentViewModel.kt
> +    private fun getBestAvailableBitmap(vectorResID: Int, rasterResID: Int): BitmapDescriptor =
Тоже самое. Лучше все вещи связанные с преобразованиями уносить в отдельные классы.

2022-12-01 14:49 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/maps/MapsFragmentViewModel.kt
> +    private fun getBestAvailableBitmap(vectorResID: Int, rasterResID: Int): BitmapDescriptor =
И название непонятное, лучше переименуй

2022-12-01 20:59 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/maps/MapsFragmentViewModel.kt
> +    private fun getBitmapDescriptorFromVector(
Вынес

2022-12-01 21:00 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/maps/MapsFragmentViewModel.kt
> +    private fun getBestAvailableBitmap(vectorResID: Int, rasterResID: Int): BitmapDescriptor =
Вынес и переименовал

2022-12-03 12:29 UTC, Ra53n approved these changes

2022-12-03 12:30 UTC, merged