Feature/refactor main screen
Ra53n/Charge_it pull request #22
Opened 2022-12-07 14:49 UTC by Stellarworker

Проведён рефакторинг кодовой базы

2022-12-07 15:14 UTC, Ra53n requested changes

2022-12-07 15:14 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/utils/AddressUtils.kt
> +fun getAddressByLocation(
Ты можешь это именно в класс объединить. Какой-нибудь GeocoderHelper

2022-12-07 15:14 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/utils/DataUtils.kt
> +        context = context,
Не стоит передавать контекст в модельки. Это плохая практика

2022-12-07 15:14 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/utils/DataUtils.kt
> +fun getChargeStationClusterItem(
Если тебе нужен контекст то ты можешь создать это как отдельный класс и через di передавать сюда контекст. Не нужно им вот так разбрасываться, это может повлечь за собой кучу ошибок.

2022-12-07 15:14 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/utils/DataUtils.kt
> +fun getChargeStationClusterItem(
И да, тоже лучше все в классы объединить

2022-12-07 15:14 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/utils/LocationUtils.kt
> +fun getDistanceBetween(firstLocation: LatLng, secondLocation: LatLng): FloatArray {
Тоже самое

2022-12-07 15:14 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/utils/MapUtils.kt
> +fun initMap(context: Context, map: GoogleMap, viewModel: MapsFragmentViewModelContract) {
Все тоже самое и про класс и про контекст

2022-12-07 15:14 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/utils/PermissionUtils.kt
> +fun isPermissionGranted(context: Context, permission: String) =
Тоже самое

2022-12-08 16:40 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/utils/AddressUtils.kt
> +fun getAddressByLocation(
Сделал

2022-12-08 16:40 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/utils/DataUtils.kt
> +        context = context,
Изменил

2022-12-08 16:40 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/utils/DataUtils.kt
> +fun getChargeStationClusterItem(
Сделал

2022-12-08 16:40 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/utils/LocationUtils.kt
> +fun getDistanceBetween(firstLocation: LatLng, secondLocation: LatLng): FloatArray {
Поменял

2022-12-08 16:40 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/utils/MapUtils.kt
> +fun initMap(context: Context, map: GoogleMap, viewModel: MapsFragmentViewModelContract) {
Исправил

2022-12-08 16:40 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/utils/PermissionUtils.kt
> +fun isPermissionGranted(context: Context, permission: String) =
Переписал

2022-12-09 15:21 UTC, Ra53n approved these changes

2022-12-09 15:21 UTC, Ra53n commented on station_info/src/main/java/chargeit/station_info/ui/StationInfoBottomSheetFragment.kt
> +                    electricStationEntity!!.lat,
Не очень хорошо через !! но ладно. Здесь можно через .let

2022-12-09 15:21 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/utils/PermissionHelper.kt
> +    ) = fragment.registerForActivityResult(
Все до знака равно можно в одну строку, а после уж переносить, так более читабельно будет

2022-12-09 15:22 UTC, merged