Feature/main screen
Ra53n/Charge_it pull request #6
Opened 2022-11-02 15:03 UTC by Stellarworker

Главный экран.

1. Реализован основной интерфейс: загрузка google-карты, строка поиска и две кнопки (экран фильтров и текущее положение пользователя).
2. API_KEY из манифеста не сработал, использую свой.
3. Реализован кликабельный маркер.

2022-11-04 11:19 UTC, Ra53n requested changes

2022-11-04 11:19 UTC, Ra53n commented on main_screen/src/androidTest/java/chargeit/main_screen/ExampleInstrumentedTest.kt
> +
Лучше тесты удалить, на них у нас особо нет времени)

2022-11-04 11:19 UTC, Ra53n commented on main_screen/src/test/java/chargeit/main_screen/ExampleUnitTest.kt
> + *
Тоже самое

2022-11-04 11:19 UTC, Ra53n commented on main_screen/src/main/AndroidManifest.xml
> +<manifest package="chargeit.core" />
Не то имя, у тебя должно быть chargeit.main_screen

2022-11-04 11:19 UTC, Ra53n commented on main_screen/src/main/AndroidManifest.xml
> +<manifest package="chargeit.main_screen" />
Все, увидел. Молодец)

2022-11-04 11:19 UTC, Ra53n commented on app/build.gradle
> +    implementation project(path: ':main_screen')
Подвинь это ниже, к строке с модулем core

2022-11-04 11:19 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/settings/Settings.kt
> +const val DEFAULT_PLACE_NAME = "Moscow"
Ты можешь сделать это значением по умолчанию через конструкцию  val name: String = "Moscow",

2022-11-04 11:19 UTC, Ra53n commented on main_screen/src/main/res/layout/fragment_maps.xml
> +        android:id="@+id/fragment_maps_map"
Лучше убрать из всех id строку - fragment_maps. У тебя же отдельной фичой реализовано, поэтому не должно быть проблем

2022-11-04 11:19 UTC, Ra53n commented on main_screen/src/main/res/values/dimens.xml
> +    <dimen name="fragment_maps_interface_margin">10dp</dimen>
Убери отовсюду fragment_maps_

2022-11-04 11:19 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +        private const val DEFAULT_PLACE_MESSAGE = "Default place"
Это лучше в строковые ресурсы убрать

2022-11-04 11:19 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +            childFragmentManager.findFragmentById(R.id.fragment_maps_map) as SupportMapFragment?
Что-то ты слишком сложно пошел. Можно через 
`binding.fragmentMapsMap.getFragment<SupportMapFragment>()`

2022-11-04 11:19 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragmentViewModel.kt
> +        name = DEFAULT_PLACE_NAME,
Если пропишешь значение по умолчанию, как я писал выше, то этого всего не надо будет

2022-11-04 11:19 UTC, Ra53n commented on main_screen/src/main/res/layout/fragment_maps.xml
> +                android:layout_width="fill_parent"
Лучше использовать match_parent. fill_parent устаревшая штука

2022-11-04 11:19 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +        view?.makeSnackbar(text = FILTER_PAGE_MESSAGE)
Тоже все через ресурсы

2022-11-04 11:19 UTC, Ra53n commented on main_screen/src/main/res/values/dimens.xml
> +    <dimen name="fragment_maps_bottom_sheet_root_peek_height">0dp</dimen>
Можешь не выносить это. Прямо так и оставить 0dp

2022-11-05 14:19 UTC, Stellarworker commented on main_screen/src/androidTest/java/chargeit/main_screen/ExampleInstrumentedTest.kt
> +
Удалил

2022-11-05 14:19 UTC, Stellarworker commented on main_screen/src/test/java/chargeit/main_screen/ExampleUnitTest.kt
> + *
И это тоже удалил

2022-11-05 14:19 UTC, Stellarworker commented on app/build.gradle
> +    implementation project(path: ':main_screen')
Подвинул

2022-11-05 14:20 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/settings/Settings.kt
> +const val DEFAULT_PLACE_NAME = "Moscow"
Сделал. Пока Place() - это временная минималистичная конструкция

2022-11-05 14:21 UTC, Stellarworker commented on main_screen/src/main/res/layout/fragment_maps.xml
> +        android:id="@+id/fragment_maps_map"
Убрал fragment_maps отовсюду

2022-11-05 14:21 UTC, Stellarworker commented on main_screen/src/main/res/values/dimens.xml
> +    <dimen name="fragment_maps_interface_margin">10dp</dimen>
Сделал

2022-11-05 14:22 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +        private const val DEFAULT_PLACE_MESSAGE = "Default place"
Перевёл в ресурсы

2022-11-05 14:22 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +            childFragmentManager.findFragmentById(R.id.fragment_maps_map) as SupportMapFragment?
Пошёл привычным путём) Поменял

2022-11-05 14:22 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragmentViewModel.kt
> +        name = DEFAULT_PLACE_NAME,
Прописал

2022-11-05 14:23 UTC, Stellarworker commented on main_screen/src/main/res/layout/fragment_maps.xml
> +                android:layout_width="fill_parent"
Поменял на match_parent

2022-11-05 14:23 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +        view?.makeSnackbar(text = FILTER_PAGE_MESSAGE)
Сделал

2022-11-05 14:23 UTC, Stellarworker commented on main_screen/src/main/res/values/dimens.xml
> +    <dimen name="fragment_maps_bottom_sheet_root_peek_height">0dp</dimen>
0dp оставил

2022-11-05 14:23 UTC, Stellarworker commented on main_screen/src/main/AndroidManifest.xml
> +<manifest package="chargeit.core" />
Уже

2022-11-05 14:24 UTC, Stellarworker commented on main_screen/src/main/AndroidManifest.xml
> +<manifest package="chargeit.main_screen" />
)

2022-11-05 15:01 UTC, Ra53n requested changes

2022-11-05 15:01 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/settings/Settings.kt
> +const val ZERO_FLOAT = 0.0F
Лучше это сделать немного по другому. Создай в модуле core файл extensions.kt. И пропиши в нем extension функции с соответствующими типами данных. Например:  String.EMPTY = ""

2022-11-08 12:39 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/settings/Settings.kt
> +const val ZERO_FLOAT = 0.0F
Сделано

2022-11-09 18:27 UTC, Ra53n requested changes

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +        private const val AFL = Manifest.permission.ACCESS_FINE_LOCATION
Лучше такое не выносить в companion object. Перенеси лучше в переменную и название лучше другое сделать, а то сразу не понятно что это такое.

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +        private const val PROVIDER = LocationManager.NETWORK_PROVIDER
Тоже самое, лучше в локальную переменную

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +    private val coroutineExceptionHandler = CoroutineExceptionHandler { _, throwable ->
Тебе надо всю логику от сюда перенести в ViewModel. Вьюшка должна заниматься только отображением, а вся бизнес-логика должна быть во viewmodel

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +            if (grantResults.isNotEmpty()
Очень тяжело читать условия, лучше упрости

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +            if (grantResults.isNotEmpty()
Можешь что-то в переменные вынести

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +    private fun getLocation(context: Context) {
Большая функция, разбей на несколько логических функций

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +    private fun getLocation(context: Context) {
И тоже всю логику уноси во viewModel

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +                        context,
Можешь в функцию вынести и передавать boolean параметр допустим isGpsTurnedOn

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +        userLocationJob = scope.launch {
Все вещи связанные с многопоточностью тем более должны быть во viewModel

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +                        thisView.hideKeyboard()
Лучше эти экстеншн функции перенести в CoreFragment. Это нехорошо, что они являются расширением, ведь они относятся только к фрагментам, а не в общем ко view. И сделать их просто функциями, которые уже определены

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +                            thisView.makeSnackbar(text = getString(R.string.empty_query_message))
Это тоже

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +        currentUserLocation?.let { location ->
Достаточно было if else. Слишком сложно получилось

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +                location?.let {
Тоже достаточно if else. Иначе просто трудно читать код

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +                view?.let { thisView ->
Можешь без этого обойтись, усложняет чтение кода. Лучше обращайся через ? если что-то надо вызвать

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +                    query?.let { thisQuery ->
Тоже самое

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +        addressLocationJob?.cancel()
Тоже разбей на логические методы

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragmentViewModel.kt
> +    val datasetLiveData: Observable<MapsFragmentDataset> = BehaviorSubject.create()
Переделай пожалуйста на LiveData, если знаешь как. Договорились что viewModel с использованием LiveData будем делать

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
>          map = googleMap
Вынеси все в отдельную функцию

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/domain/MapsFragmentDataset.kt
> +data class MapsFragmentDataset(
Что ты под этим классом подразумевал?

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +    private val viewModelDisposable = CompositeDisposable()
Тебе это не нужно, мы на LiveData

2022-11-09 18:27 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +                showAddress(addresses.component1(), USER_LOCATION_ZOOM_LEVEL, true)
Использую first() вместо component1

2022-11-14 22:50 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +        private const val AFL = Manifest.permission.ACCESS_FINE_LOCATION
Исправил

2022-11-14 22:50 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +        private const val PROVIDER = LocationManager.NETWORK_PROVIDER
Сделал

2022-11-14 22:51 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +    private val coroutineExceptionHandler = CoroutineExceptionHandler { _, throwable ->
Перенёс туда определение текущих координат и поиск адресов

2022-11-14 22:51 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +            if (grantResults.isNotEmpty()
Переписал

2022-11-14 22:52 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +    private fun getLocation(context: Context) {
Сделал

2022-11-14 22:52 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +                        context,
Переписал

2022-11-14 22:52 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +        userLocationJob = scope.launch {
Перенёс туда

2022-11-14 22:52 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +                        thisView.hideKeyboard()
Перенёс

2022-11-14 22:53 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +                            thisView.makeSnackbar(text = getString(R.string.empty_query_message))
Перенёс

2022-11-14 22:53 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +        currentUserLocation?.let { location ->
Переписал

2022-11-14 22:53 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +                location?.let {
Переписал

2022-11-14 22:54 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +                view?.let { thisView ->
Переделал

2022-11-14 22:54 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +                    query?.let { thisQuery ->
Переделал

2022-11-14 22:56 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/view/MapsFragment.kt
> +        addressLocationJob?.cancel()
Переписал

2022-11-14 22:56 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragmentViewModel.kt
> +    val datasetLiveData: Observable<MapsFragmentDataset> = BehaviorSubject.create()
Переделал

2022-11-14 22:56 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
>          map = googleMap
Вынес

2022-11-14 23:02 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/domain/MapsFragmentDataset.kt
> +data class MapsFragmentDataset(
MapsFragmentDataset это класс, в идеальном случае содержащий всю нужную информацию для View. Задача ViewModel - сформировать его и отдать. Задача View - забрать его и показать информацию оттуда с как можно более минимальной обработкой. В нашем случае он может содержать в себе список зарядных станций + ещё что-то, что нужно будет отображать.

2022-11-14 23:02 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +    private val viewModelDisposable = CompositeDisposable()
Исправил

2022-11-14 23:02 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +                showAddress(addresses.component1(), USER_LOCATION_ZOOM_LEVEL, true)
Сделал

2022-11-15 15:34 UTC, Ra53n requested changes

2022-11-15 15:34 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/domain/MapsFragmentDataset.kt
> +data class MapsFragmentDataset(
Тебе не нужно все данные собирать в одном объекте для view. Тогда у тебя при любом изменении будет весь экран преобразовываться, тогда у тебя будет нагрузка на UI, тогда будут лаги. 
Это насколько я понимаю модель станций или возможно вообще всех мест. Если это модель всех мест, которые как-то будут отмечаться на карте, то тебе нужно их разделить и назвать соответствующе. Например модель для электро-станций можно назвать ElectricStationUiModel.

2022-11-15 15:34 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/settings/Settings.kt
> +const val DEVICE_LOCATION_REFRESH_PERIOD = 6000L
Константы которые используются в одном месте можно прописывать в companion object того класса, где она используется

2022-11-15 15:34 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragmentViewModel.kt
> +    val locationLiveData: MutableLiveData<LocationState> = MutableLiveData(),
А зачем ты LiveData передаешь в конструкторе? Они должны быть публичными переменными которые будут доступны по обращению к объекту класса

2022-11-15 15:34 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragmentViewModel.kt
> +    val locationLiveData: MutableLiveData<LocationState> = MutableLiveData(),
И создаваться тоже должны во вью модели

2022-11-15 15:34 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/di/modules.kt
> +    single<MutableLiveData<DatasetState>>(named("DatasetState")) { MutableLiveData() }
Здесь это не нужно

2022-11-15 15:34 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/domain/DataSetState.kt
> +sealed class DatasetState {
Непонятно что это, переименуй

2022-11-15 15:34 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
>      private var currentAddressMarker: Marker? = null
У тебя все еще слишком много логики во вью. Всю логику надо хранить именно во viewModel

2022-11-15 15:34 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +    private fun whenEmptyQuery() {
Немного неправильный нейминг. Это неправильно называть функцию на условии когда она появляется. Надо называть так, чтобы было понятно что она делает. В данном случае можно убрать лишнюю функцию и сразу вызывать snaсkBar. По логике в коде в принципе понятно когда она появляется.

2022-11-15 15:34 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +                    when (resultQuery.isNotBlank()) {
У тебя всего два варианта. Лучше использовать if else

2022-11-15 15:34 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +            when (shouldShowRequestPermissionRationale(PERMISSION)) {
Тоже if else

2022-11-15 15:34 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +        when (isPermissionGranted(requireContext(), PERMISSION)) {
В общем везде поправь)

2022-11-15 15:34 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +    private fun whenAddressIsNotEmpty(address: Address) {
Тоже нейминг. Проще назвать onAdressChanged

2022-11-15 15:34 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +        val addresses = mapsFragmentViewModel.getAddressesByQuery(query)
ViewModel не должна иметь такие методы, которые напрямую бы что-то возвращали view. Все общение должно происходить через viewModel.

2022-11-15 15:34 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +    private fun whenAddressIsEmpty() {
Нейминг

2022-11-15 15:34 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +    private fun whenDatasetIsSuccess(mapsFragmentDataset: MapsFragmentDataset) {
В общем тоже везде поправь

2022-11-15 15:34 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +    private fun showRationaleDialog() {
По сути тебе не нужны такие методы. Прямо в коде можешь все это прописывать. По ресурсам понятно почему это происходит и что имелось ввиду.

2022-11-15 15:34 UTC, Ra53n commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +    private fun showLastLocationUnknownDialog() {
Постарайся в принципе не делать функцию которая вызывает тоже функцию в одну строку

2022-11-19 23:25 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/domain/MapsFragmentDataset.kt
> +data class MapsFragmentDataset(
Реорганизовал данные

2022-11-19 23:26 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/settings/Settings.kt
> +const val DEVICE_LOCATION_REFRESH_PERIOD = 6000L
Перенёс

2022-11-19 23:26 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragmentViewModel.kt
> +    val locationLiveData: MutableLiveData<LocationState> = MutableLiveData(),
Сделал

2022-11-19 23:26 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/di/modules.kt
> +    single<MutableLiveData<DatasetState>>(named("DatasetState")) { MutableLiveData() }
Убрал

2022-11-19 23:26 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/domain/DataSetState.kt
> +sealed class DatasetState {
Исправил

2022-11-19 23:27 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
>      private var currentAddressMarker: Marker? = null
Вынес больше логики

2022-11-19 23:27 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +    private fun whenEmptyQuery() {
Переименовал

2022-11-19 23:27 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +                    when (resultQuery.isNotBlank()) {
Исправил

2022-11-19 23:27 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +            when (shouldShowRequestPermissionRationale(PERMISSION)) {
Исправил

2022-11-19 23:28 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +        when (isPermissionGranted(requireContext(), PERMISSION)) {
Сделал

2022-11-19 23:30 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +    private fun whenAddressIsNotEmpty(address: Address) {
Переделал

2022-11-19 23:30 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +        val addresses = mapsFragmentViewModel.getAddressesByQuery(query)
Исправил

2022-11-19 23:30 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +    private fun whenAddressIsEmpty() {
Поменял

2022-11-19 23:30 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +    private fun whenDatasetIsSuccess(mapsFragmentDataset: MapsFragmentDataset) {
Поправил

2022-11-19 23:32 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +    private fun showLastLocationUnknownDialog() {
Постараюсь)

2022-11-19 23:33 UTC, Stellarworker commented on main_screen/src/main/java/chargeit/main_screen/ui/MapsFragment.kt
> +    private fun showRationaleDialog() {
Думаю над этим

2022-11-20 07:41 UTC, Ra53n approved these changes

2022-11-20 07:43 UTC, Ra53n approved these changes

2022-11-20 07:45 UTC, merged