Created databases and added them to di
Ra53n/Charge_it pull request #8
Opened 2022-11-06 15:18 UTC by Oduvan58

Прошу проверить, вроде исправил замечания

2022-11-06 18:14 UTC, Ra53n requested changes

2022-11-06 18:14 UTC, Ra53n commented on app/src/main/java/chargeit/app/room/CarDao.kt
> +package chargeit.app.room
Раздели еще пожалуйста на папочки. Не хорошо что Dao, Database и Entity все вперемешку лежат

2022-11-06 18:14 UTC, Ra53n commented on app/src/main/java/chargeit/app/room/CarDatabase.kt
> +                instance = Room.databaseBuilder(context!!, CarDatabase::class.java, DB_NAME)
Зачем ты передаешь nullable Context а потом говоришь что он точно не null?

2022-11-06 18:14 UTC, Ra53n commented on app/src/main/java/chargeit/app/room/CarDatabase.kt
> +                instance = Room.databaseBuilder(context!!, CarDatabase::class.java, DB_NAME)
Сделай его обычным, все равно скорее всего applicationContext будем передавать через di

2022-11-06 18:14 UTC, Ra53n commented on app/src/main/java/chargeit/app/room/ElectricStationDatabase.kt
> +                    Room.databaseBuilder(context!!, ElectricStationDatabase::class.java, DB_NAME)
Везде так сделай пожалуйста

2022-11-13 15:30 UTC, Oduvan58 commented on app/src/main/java/chargeit/app/room/CarDao.kt
> +package chargeit.app.room
Исправил

2022-11-13 15:30 UTC, Oduvan58 commented on app/src/main/java/chargeit/app/room/CarDatabase.kt
> +                instance = Room.databaseBuilder(context!!, CarDatabase::class.java, DB_NAME)
Исправил

2022-11-13 15:30 UTC, Oduvan58 commented on app/src/main/java/chargeit/app/room/ElectricStationDatabase.kt
> +                    Room.databaseBuilder(context!!, ElectricStationDatabase::class.java, DB_NAME)
Исправил

2022-11-13 15:53 UTC, Ra53n approved these changes

2022-11-13 15:54 UTC, merged